[tox]
envlist =
    py{311,312,313,314}-test
    codestyle
isolated_build = True

[testenv]
setenv =
    MPLBACKEND = agg
extras = test
commands = pytest {posargs}

[testenv:codestyle]
skip_install = true
description = Run all style and file checks with pre-commit
deps =
    pre-commit
commands =
    pre-commit install-hooks
    pre-commit run {posargs:--color always --all-files --show-diff-on-failure}
