# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: CI Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    # branches: # only build on PRs against 'main' if you need to further limit when CI is run.
    #    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARCH_ON_CI: "normal"
  IS_CRON: "false"

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v3
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      setenv: |
        ARCH_ON_CI: "normal"
        IS_CRON: "false"
      submodules: false
      coverage: ""
      envs: |
        - name: Code style checks
          linux: codestyle

        - name: Python 3.14, measuring coverage
          linux: py314-test
          coverage: codecov
